// <auto-generated />
namespace EFLibForApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addgwd_ICRIS_DisOrders : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addgwd_ICRIS_DisOrders));
        
        string IMigrationMetadata.Id
        {
            get { return "201604220616019_addgwd_ICRIS_DisOrders"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
